suppressPackageStartupMessages({library(tidyverse);library(cowplot)})
# Plot-only RQ2 entry point. Reads frozen outputs from scripts/12_rq2_analysis.R.
COND_RDS<-"data/derived/rq2/rq2_condition_long.rds";GAMMA_RDS<-"data/derived/rq2/rq2_gamma_long.rds";COND_GEOM_CSV<-"results/rq2/rq2_conditional_geometry.csv";ANCHOR_CSV<-"results/rq2/rq2_anchor_configurations.csv";COND_EXAMPLE_CSV<-"results/rq2/rq2_conditional_examples.csv";MODEL_PERF_CSV<-"results/rq2/rq2_model_performance.csv";GAMMA_SUMMARY_CSV<-"results/rq2/rq2_gamma_summary.csv";GAMMA_PAIR_CSV<-"results/rq2/rq2_gamma_pair_summary.csv";GAMMA_EXAMPLE_CSV<-"results/rq2/rq2_gamma_examples.csv";STRONG_EXAMPLE_CSV<-"results/rq2/rq2_strong_coupling_example.csv";SCOPE_CSV<-"results/rq2/rq2_interaction_scope.csv";FIG_DIR<-"results/figures"
reqfiles<-c(COND_RDS,GAMMA_RDS,COND_GEOM_CSV,ANCHOR_CSV,COND_EXAMPLE_CSV,MODEL_PERF_CSV,GAMMA_SUMMARY_CSV,GAMMA_PAIR_CSV,GAMMA_EXAMPLE_CSV,STRONG_EXAMPLE_CSV,SCOPE_CSV);for(p in reqfiles)if(!file.exists(p))stop("Missing RQ2 artifact: ",p,". Run scripts/12_rq2_analysis.R first.");dir.create(FIG_DIR,recursive=TRUE,showWarnings=FALSE)
METRIC_CLASSES<-c("duration","exposure history","level","spectrum","temporal dynamics","timing");DIM_TITLES<-c(placement="Placement",optical="Optical proxy",temporal="Temporal resolution",duration="Monitoring duration");PAIR_LEVELS<-c("placement × optical","placement × temporal","optical × temporal");STATE_LEVELS<-c("Low","Middle","High");MODEL_LEVELS<-c("external_context","exposure_state","joint");MODEL_LABELS<-c(external_context="External",exposure_state="Exposure state",joint="Joint")
base_square_theme<-theme_minimal(base_size=8)+theme(aspect.ratio=1,panel.grid.minor=element_blank(),plot.title=element_text(size=9,margin=margin(b=3)),plot.margin=margin(4,5,4,5),legend.position="none")
asinh_display<-scales::transform_asinh()
cond<-readRDS(COND_RDS)|>mutate(metric_class=factor(metric_class,levels=METRIC_CLASSES),state_bin_label=factor(as.character(state_bin_label),levels=STATE_LEVELS));gamma<-readRDS(GAMMA_RDS)|>mutate(metric_class=factor(metric_class,levels=METRIC_CLASSES));cg<-readr::read_csv(COND_GEOM_CSV,show_col_types=FALSE)|>mutate(metric_class=factor(metric_class,levels=METRIC_CLASSES),state_bin_label=factor(state_bin_label,levels=STATE_LEVELS));anchors<-readr::read_csv(ANCHOR_CSV,show_col_types=FALSE);examples<-readr::read_csv(COND_EXAMPLE_CSV,show_col_types=FALSE);perf<-readr::read_csv(MODEL_PERF_CSV,show_col_types=FALSE)|>mutate(metric_class=factor(metric_class,levels=METRIC_CLASSES),model_family=factor(model_family,levels=MODEL_LEVELS),model_label=factor(MODEL_LABELS[as.character(model_family)],levels=unname(MODEL_LABELS)));gs<-readr::read_csv(GAMMA_SUMMARY_CSV,show_col_types=FALSE)|>mutate(metric_class=factor(metric_class,levels=METRIC_CLASSES),dimension_pair=factor(dimension_pair,levels=PAIR_LEVELS));gp<-readr::read_csv(GAMMA_PAIR_CSV,show_col_types=FALSE)|>mutate(dimension_pair=factor(dimension_pair,levels=PAIR_LEVELS));ge<-readr::read_csv(GAMMA_EXAMPLE_CSV,show_col_types=FALSE);strong<-readr::read_csv(STRONG_EXAMPLE_CSV,show_col_types=FALSE);scope<-readr::read_csv(SCOPE_CSV,show_col_types=FALSE)
metric_legend<-cowplot::get_legend(ggplot(tibble(metric_class=factor(METRIC_CLASSES,levels=METRIC_CLASSES),x=seq_along(METRIC_CLASSES),y=1),aes(x,y,color=metric_class))+geom_point(size=2)+scale_color_discrete(drop=FALSE)+guides(color=guide_legend(title="metric class",nrow=1,byrow=TRUE))+theme_void(base_size=8)+theme(legend.position="bottom"))

# Fig 2a: empirical conditional distributions for algorithmically selected examples.
ids<-examples|>transmute(example_id=paste(dimension,configuration,metric,sep="|"),example_label=paste0(DIM_TITLES[dimension],": ",metric))
exd<-cond|>mutate(example_id=paste(dimension,configuration,metric,sep="|"))|>inner_join(ids,by="example_id")|>filter(available,is.finite(e),!is.na(state_bin_label))
p2a<-ggplot(exd,aes(e,color=state_bin_label,fill=state_bin_label))+geom_density(alpha=.14,linewidth=.45,adjust=.9)+geom_vline(xintercept=0,linewidth=.28,color="grey45")+facet_wrap(~example_label,scales="free",ncol=2)+labs(title="a  Conditional distortion distributions",x="standardized signed distortion (e)",y="density",color="reference state",fill="reference state")+theme_minimal(base_size=7.4)+theme(aspect.ratio=1,panel.grid.minor=element_blank(),strip.text=element_text(size=6.4),plot.title=element_text(size=9),legend.position="bottom",plot.margin=margin(4,5,4,5))
conditional_ab_panel<-function(dim,letter){d<-cg|>filter(dimension==dim)|>semi_join(anchors|>filter(dimension==dim),by=c("dimension","configuration"))|>filter(is.finite(A_conditional),is.finite(B_conditional))|>arrange(metric,configuration,state_bin);if(!nrow(d))return(ggplot()+annotate("text",x=0,y=0,label="Not estimable",size=3)+xlim(-1,1)+ylim(-1,1)+labs(title=paste0(letter,"  ",DIM_TITLES[[dim]]))+base_square_theme);hi<-d|>group_by(metric,configuration)|>slice_max(state_bin,n=1,with_ties=FALSE)|>ungroup();lab<-hi|>slice_max(A_conditional,n=3,with_ties=FALSE);lim<-max(c(d$A_conditional,abs(d$B_conditional)),na.rm=TRUE)*1.08;ggplot(d,aes(B_conditional,A_conditional,color=metric_class))+geom_abline(slope=c(-1,1),intercept=0,linetype=2,linewidth=.3,color="grey65")+geom_path(aes(group=interaction(metric,configuration)),color="grey42",alpha=.55,linewidth=.48,lineend="round")+geom_point(aes(shape=state_bin_label),size=1.15,alpha=.78)+geom_point(data=hi,size=1.7,alpha=.95,show.legend=FALSE)+geom_text(data=lab,aes(label=metric),size=1.85,vjust=-.65,check_overlap=TRUE,show.legend=FALSE)+scale_color_discrete(drop=FALSE)+scale_shape_manual(values=c(Low=1,Middle=16,High=17))+scale_x_continuous(transform=asinh_display,limits=c(-lim,lim),expand=expansion(mult=.025))+scale_y_continuous(transform=asinh_display,limits=c(0,lim),expand=expansion(mult=.025))+labs(title=paste0(letter,"  ",DIM_TITLES[[dim]]),x="conditional B",y="conditional A")+base_square_theme}
p2b<-conditional_ab_panel("placement","b");p2c<-conditional_ab_panel("optical","c");p2d<-conditional_ab_panel("temporal","d");p2e<-conditional_ab_panel("duration","e")

# Fig 2f: predictability vs transportability. Same metric/config/model fit appears
# once; distance below y=x is the cross-site portability loss.
perfwide<-perf|>filter(is.finite(r2),validation_scheme%in%c("participant_grouped","leave_site_out"))|>select(dimension,configuration,metric,metric_class,outcome,model_family,model_label,validation_scheme,r2)|>pivot_wider(names_from=validation_scheme,values_from=r2)|>filter(is.finite(participant_grouped),is.finite(leave_site_out))
if(nrow(perfwide)){lims<-range(c(perfwide$participant_grouped,perfwide$leave_site_out),finite=TRUE);pad<-.05*diff(lims);if(!is.finite(pad)||pad==0)pad<-.1;lims<-c(lims[1]-pad,lims[2]+pad);p2f<-ggplot(perfwide,aes(participant_grouped,leave_site_out,color=model_label,shape=model_label))+geom_abline(slope=1,intercept=0,linetype=2,linewidth=.35,color="grey55")+geom_point(size=.95,alpha=.5)+facet_wrap(~outcome,ncol=1)+coord_equal(xlim=lims,ylim=lims)+labs(title="f  Predictability → transportability",x="grouped-participant CV R²",y="leave-site-out R²",color=NULL,shape=NULL)+theme_minimal(base_size=7.4)+theme(aspect.ratio=1,panel.grid.minor=element_blank(),plot.title=element_text(size=9),legend.position="bottom",legend.text=element_text(size=6.5),plot.margin=margin(4,5,4,5))}else{p2f<-ggplot()+annotate("text",x=0,y=0,label="Prediction models not estimable",size=3)+xlim(-1,1)+ylim(-1,1)+labs(title="f  Predictability → transportability")+base_square_theme}
fig2body<-plot_grid(p2a,p2b,p2c,p2d,p2e,p2f,ncol=3,align="hv",axis="tblr",rel_widths=rep(1,3),rel_heights=c(1,1));fig2<-plot_grid(fig2body,metric_legend,ncol=1,rel_heights=c(1,.07));ggsave(file.path(FIG_DIR,"Fig2_RQ2.pdf"),fig2,width=12.2,height=8.4,useDingbats=FALSE);ggsave(file.path(FIG_DIR,"Fig2_RQ2.png"),fig2,width=12.2,height=8.4,dpi=220)

# Fig 3a: second-order contrast schematic.
scells<-tribble(~x,~y,~label,0,0,"reference\nM00",1,0,"a changed\nMa0",0,1,"b changed\nM0b",1,1,"a + b\nMab")
p3a<-ggplot(scells,aes(x,y))+geom_tile(width=.62,height=.42,fill="grey94",color="grey40",linewidth=.4)+geom_text(aes(label=label),size=2.5)+annotate("segment",x=.3,xend=.7,y=0,yend=0,arrow=grid::arrow(length=grid::unit(1.3,"mm")),linewidth=.35)+annotate("segment",x=.3,xend=.7,y=1,yend=1,arrow=grid::arrow(length=grid::unit(1.3,"mm")),linewidth=.35)+annotate("text",x=.5,y=.53,label="γ = Δa|b − Δa|0",size=3)+coord_equal(xlim=c(-.45,1.45),ylim=c(-.45,1.45),clip="off")+labs(title="a  Second-order interaction distortion")+theme_void(base_size=8)+theme(aspect.ratio=1,plot.title=element_text(size=9),plot.margin=margin(4,5,4,5))
gids<-ge|>transmute(id=paste(dimension_pair,a_configuration,b_configuration,metric,sep=" | "),example_type);ged<-gamma|>filter(available,is.finite(gamma))|>mutate(id=paste(dimension_pair,a_configuration,b_configuration,metric,sep=" | "))|>inner_join(gids,by="id")
p3b<-ggplot(ged,aes(gamma,fill=example_type))+geom_density(alpha=.38,color=NA,adjust=.85)+geom_vline(xintercept=0,linewidth=.28,color="grey40")+facet_wrap(~example_type,scales="free",ncol=2)+guides(fill="none")+labs(title="b  Empirical D(γ)",x="standardized interaction distortion (γ)",y="density")+theme_minimal(base_size=7.2)+theme(aspect.ratio=1,panel.grid.minor=element_blank(),strip.text=element_text(size=6.2),plot.title=element_text(size=9),plot.margin=margin(4,5,4,5))
if(nrow(gs)){lim<-max(c(gs$Q_mean_absolute,abs(gs$R_mean_signed)),na.rm=TRUE)*1.06;lab<-gs|>slice_max(Q_mean_absolute,n=5,with_ties=FALSE);p3c<-ggplot(gs,aes(R_mean_signed,Q_mean_absolute,color=metric_class))+geom_abline(slope=c(-1,1),intercept=0,linetype=2,linewidth=.3,color="grey63")+geom_point(aes(shape=dimension_pair),size=1.05,alpha=.67)+geom_text(data=lab,aes(label=metric),size=1.8,vjust=-.6,check_overlap=TRUE,show.legend=FALSE)+scale_color_discrete(drop=FALSE)+scale_x_continuous(transform=asinh_display,limits=c(-lim,lim),expand=expansion(mult=.025))+scale_y_continuous(transform=asinh_display,limits=c(0,lim),expand=expansion(mult=.025))+labs(title="c  Interaction geometry",x="R: mean signed γ",y="Q: mean absolute γ")+base_square_theme}else p3c<-ggplot()+annotate("text",x=0,y=0,label="No gamma summaries")+xlim(-1,1)+ylim(-1,1)+labs(title="c  Interaction geometry")+base_square_theme
p3d<-ggplot(gp,aes(dimension_pair,median_Q))+geom_errorbar(aes(ymin=q25_Q,ymax=q75_Q),width=.12,linewidth=.45,color="grey45")+geom_point(size=2.2)+coord_flip()+labs(title="d  Overall cross-dimensional dependence",x=NULL,y="median Q across metric-configurations")+base_square_theme+theme(axis.text.y=element_text(size=7))
if(nrow(strong)){sid<-strong|>transmute(id=paste(dimension_pair,a_configuration,b_configuration,metric,sep=" | "))|>pull(id);sd<-gamma|>filter(available,is.finite(gamma))|>mutate(id=paste(dimension_pair,a_configuration,b_configuration,metric,sep=" | "))|>filter(id==sid)|>select(marginal_a_ref,marginal_a_at_b)|>pivot_longer(everything(),names_to="b_state",values_to="marginal_effect")|>mutate(b_state=recode(b_state,marginal_a_ref="b at reference",marginal_a_at_b="b changed"));ss<-sd|>group_by(b_state)|>summarise(mean=mean(marginal_effect),q25=quantile(marginal_effect,.25),q75=quantile(marginal_effect,.75),.groups="drop");p3e<-ggplot(ss,aes(b_state,mean,group=1))+geom_hline(yintercept=0,linewidth=.3,color="grey60")+geom_line(linewidth=.55,color="grey40")+geom_errorbar(aes(ymin=q25,ymax=q75),width=.1,linewidth=.42)+geom_point(size=2)+labs(title=paste0("e  Strong coupling: ",strong$metric[1]),x=NULL,y="marginal effect of dimension a")+base_square_theme+theme(axis.text.x=element_text(angle=15,hjust=1))}else p3e<-ggplot()+annotate("text",x=0,y=0,label="No strong-coupling example")+xlim(-1,1)+ylim(-1,1)+labs(title="e  Strong coupling")+base_square_theme

# Fig 3f: explicit scope/observability matrix rather than leaving a blank panel.
scope<-scope|>mutate(a=sub(" × .*","",dimension_pair),b=sub(".* × ","",dimension_pair),status=factor(status,levels=c("estimated","not population-estimated","unavailable")))
p3f<-ggplot(scope,aes(a,b))+geom_tile(aes(fill=status),color="white",linewidth=.8)+geom_text(aes(label=case_when(status=="estimated"~"estimated",status=="not population-estimated"~"limited",TRUE~"unavailable")),size=2.2)+scale_fill_manual(values=c("estimated"="grey55","not population-estimated"="grey85","unavailable"="white"),drop=FALSE)+labs(title="f  Empirical interaction scope",x=NULL,y=NULL,fill=NULL)+theme_minimal(base_size=7.2)+theme(aspect.ratio=1,panel.grid=element_blank(),axis.text.x=element_text(angle=25,hjust=1),legend.position="bottom",plot.title=element_text(size=9),plot.margin=margin(4,5,4,5))
fig3body<-plot_grid(p3a,p3b,p3c,p3d,p3e,p3f,ncol=3,align="hv",axis="tblr",rel_widths=rep(1,3),rel_heights=c(1,1));fig3<-plot_grid(fig3body,metric_legend,ncol=1,rel_heights=c(1,.07));ggsave(file.path(FIG_DIR,"Fig3_RQ2.pdf"),fig3,width=12.2,height=8.4,useDingbats=FALSE);ggsave(file.path(FIG_DIR,"Fig3_RQ2.png"),fig3,width=12.2,height=8.4,dpi=220)
message("RQ2 figures complete: Fig2_RQ2 + Fig3_RQ2")
